### ISSUE TITLE
Link Error 

### ISSUE THREAD

**Issue by Ye980226** [dtolnay/cxx#584] opened 2020-12-18 13:48 UTC
I am sorry!maybe I have to bother you.I am a green hand.I don't know whether I miss some important points.
And I have done nothing. just include!("demo/include/gmtrade_def.h");and define a enum.
my tiny project is here. https://github.com/Ye980226/gmtrade-rs/blob/main/src/main.rs#L4
I search everything and I can't found the answer.
The following is my input and output.
```
$ cargo run  --verbose
       Fresh cc v1.0.66
       Fresh unicode-xid v0.2.1
       Fresh unicode-width v0.1.8
       Fresh cxxbridge-flags v1.0.18
       Fresh lazy_static v1.4.0
       Fresh scratch v1.0.0
       Fresh winapi v0.3.9
       Fresh winapi-util v0.1.5
       Fresh termcolor v1.1.2
       Fresh codespan-reporting v0.9.5
       Fresh proc-macro2 v1.0.24
       Fresh quote v1.0.7
       Fresh syn v1.0.54
       Fresh cxx-build v1.0.18
       Fresh cxxbridge-macro v1.0.18
warning: Hard linking files in the incremental compilation cache failed. Copying files instead. Consider moving the cache directory to a file system which supports hard linking in session dir `\\?\K:\rust_program\demo\target\debug\incremental\build_script_build-3qbxcyctrjdpx\s-fu3duhz3m5-k7jcxs-working`

warning: 1 warning emitted

       Fresh link-cplusplus v1.0.4
       Fresh cxx v1.0.18
   Compiling demo v0.1.0 (K:\rust_program\demo)
     Running `rustc --crate-name demo --edition=2018 'src\main.rs' --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=d0d8b0ee93c8a81d --out-dir 'K:\rust_program\demo\target\debug\deps' -C 'incremental=K:\rust_program\demo\target\debug\incremental' -L 'dependency=K:\rust_program\demo\target\debug\deps' --extern 'cxx=K:\rust_program\demo\target\debug\deps\libcxx-1fc3904635de373d.rlib' -L 'native=D:\visual studio\VC\atlmfc\lib\amd64' -L 'native=K:\rust_program\demo\target\debug\build\demo-9c4812e458db36f7\out' -l static=gmtrade-rs -L 'native=D:\visual studio\VC\atlmfc\lib\amd64' -L 'native=K:\rust_program\demo\target\debug\build\cxx-6fcf02f70694e17a\out' -L 'native=D:\visual studio\VC\atlmfc\lib\amd64' -L 'native=K:\rust_program\demo\target\debug\build\link-cplusplus-96f3c6e4cc298ef7\out'`
error: linking with `link.exe` failed: exit code: 1000
  |
  = note: "D:\\visual studio\\VC\\bin\\amd64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "K:\\rust_program\\demo\\target\\debug\\deps\\demo.13t42bfl902zwogc.rcgu.o" "K:\\rust_program\\demo\\target\\debug\\deps\\demo.2247exxwhb8l9ggt.rcgu.o" "K:\\rust_program\\demo\\target\\debug\\deps\\demo.2e179jm76ve3pxz6.rcgu.o" "K:\\rust_program\\demo\\target\\debug\\deps\\demo.2koymhg8um6aemox.rcgu.o" "K:\\rust_program\\demo\\target\\debug\\deps\\demo.4ns87efg5fijrquj.rcgu.o" "K:\\rust_program\\demo\\target\\debug\\deps\\demo.54gnxsl1bl0ntkg.rcgu.o" "K:\\rust_program\\demo\\target\\debug\\deps\\demo.5fkv5m9b4i2gpa5u.rcgu.o" "K:\\rust_program\\demo\\target\\debug\\deps\\demo.6u55op6pyib0qjl.rcgu.o" "/OUT:K:\\rust_program\\demo\\target\\debug\\deps\\demo.exe" "K:\\rust_program\\demo\\target\\debug\\deps\\demo.2vkoyg20ywrbuez6.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:K:\\rust_program\\demo\\target\\debug\\deps" "/LIBPATH:D:\\visual studio\\VC\\atlmfc\\lib\\amd64" "/LIBPATH:K:\\rust_program\\demo\\target\\debug\\build\\demo-9c4812e458db36f7\\out" "/LIBPATH:D:\\visual studio\\VC\\atlmfc\\lib\\amd64" "/LIBPATH:K:\\rust_program\\demo\\target\\debug\\build\\cxx-6fcf02f70694e17a\\out" "/LIBPATH:D:\\visual studio\\VC\\atlmfc\\lib\\amd64" "/LIBPATH:K:\\rust_program\\demo\\target\\debug\\build\\link-cplusplus-96f3c6e4cc298ef7\\out" "/LIBPATH:C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "gmtrade-rs.lib" "/WHOLEARCHIVE:gmtrade-rs.lib" "K:\\rust_program\\demo\\target\\debug\\deps\\libcxx-1fc3904635de373d.rlib" "K:\\rust_program\\demo\\target\\debug\\deps\\liblink_cplusplus-98602115c1324050.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-f771f8d0374ceeb1.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-9049f341d2774a65.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-6a47dea777db971c.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-a3b06009982e3d9c.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-ebb710aea302de49.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-4304b0c1525af3c3.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-c70f620fc91130c5.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-3b06f844280b3802.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-86edfc7ab798fc86.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-3aa1c50c964075c2.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-3ec787c945bbba26.rlib" "C:\\Users\\Administrator.XB-20191227BPBU\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-937aede5bfe8081e.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: Non-UTF-8 output: LINK : fatal error LNK1000: \xd4\xda 000000013F394241 \xb3\xf6\xcf\xd6\xce\xb4\xd6\xaa\xb4\xed\xce\xf3\xa3\xbb\xc7\xeb\xb2\xce\xbf\xbc\xce\xc4\xb5\xb5\xd6\xd0\xb5\xc4\xbc\xbc\xca\xf5\xd6\xa7\xb3\xd6\xd1\xa1\xcf\xee\r\n

error: aborting due to previous error

error: could not compile `demo`

Caused by:
  process didn't exit successfully: `rustc --crate-name demo --edition=2018 'src\main.rs' --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=d0d8b0ee93c8a81d --out-dir 'K:\rust_program\demo\target\debug\deps' -C 'incremental=K:\rust_program\demo\target\debug\incremental' -L 'dependency=K:\rust_program\demo\target\debug\deps' --extern 'cxx=K:\rust_program\demo\target\debug\deps\libcxx-1fc3904635de373d.rlib' -L 'native=D:\visual studio\VC\atlmfc\lib\amd64' -L 'native=K:\rust_program\demo\target\debug\build\demo-9c4812e458db36f7\out' -l static=gmtrade-rs -L 'native=D:\visual studio\VC\atlmfc\lib\amd64' -L 'native=K:\rust_program\demo\target\debug\build\cxx-6fcf02f70694e17a\out' -L 'native=D:\visual studio\VC\atlmfc\lib\amd64' -L 'native=K:\rust_program\demo\target\debug\build\link-cplusplus-96f3c6e4cc298ef7\out'` (exit code: 1)
```

**Comment by dtolnay** [comment] 2020-12-18 18:25
I was not able to reproduce this.

<pre>
$ <b>cargo run</b>
   <i>Compiling proc-macro2 v1.0.24</i>
   <i>Compiling cc v1.0.66</i>
   <i>Compiling unicode-xid v0.2.1</i>
   <i>Compiling syn v1.0.54</i>
   <i>Compiling scratch v1.0.0</i>
   <i>Compiling termcolor v1.1.2</i>
   <i>Compiling cxxbridge-flags v1.0.18</i>
   <i>Compiling unicode-width v0.1.8</i>
   <i>Compiling lazy_static v1.4.0</i>
   <i>Compiling codespan-reporting v0.9.5</i>
   <i>Compiling quote v1.0.7</i>
   <i>Compiling link-cplusplus v1.0.4</i>
   <i>Compiling cxx v1.0.18</i>
   <i>Compiling cxx-build v1.0.18</i>
   <i>Compiling cxxbridge-macro v1.0.18</i>
   <i>Compiling demo v0.1.0 (/git/tmp/gmtrade-rs)</i>
    <i>Finished dev [unoptimized + debuginfo] target(s) in 10.23s</i>
     <i>Running `target/debug/demo`</i>
<b>success </b>
<b>Hello, world!</b>
</pre>

It seems specific to your linker. The error from the linker says `Non-UTF-8 output` and several of the source files in your repo are invalid UTF-8, so it could be a linker bug dealing with non-UTF-8 symbols. I would recommend trying with all source files validly encoded in UTF-8.

I'll close this issue since I haven't found any indication that the error is related to CXX, as opposed to general C++ compilation woes.

**Closed by dtolnay** 2020-12-18 18:25 UTC
