### ISSUE TITLE
Windows support? 

### ISSUE THREAD

**Issue by pravic** [dtolnay/cxx#6] opened 2020-01-09 05:41 UTC
Can I use this bridge with -msvc targets? 

An outstanding idea for the interop, thank you for it, by the way.

**Comment by dtolnay** [comment] 2020-01-09 21:56
I don't know hardly anything about Windows. :disappointed: Someone would need to try it out; I don't know of anything that would block this design from working just as well on msvc -- but I'm also not sure that if there were a blocker, I *would* know.

#8 calls out that Box construction in our current binding may not work on msvc because it isn't written using `std::addressof` and `::new`, but I haven't dug into the implications of that. Sounds like something we can fix.

In any case, any necessary fixes for Windows support would be appreciated!

I'll leave this issue open until someone is able to send a PR adding a continuous integration build on Windows.

**Comment by slurps-mad-rips** [comment] 2020-01-10 01:16
Just a slight note: MSVC does support these features and has for quite some time. The issue is more with the tooling and toolchain aspects.

With a little bit of work, a cmake shim (or other build tooling) file could be generated so that an "imported" bridge target is available for users as part of the `build.rs` process.

This would also allow you to remove any command line generation work and leave it up to cmake, meson, or whomever. In the case of CMake, you could then parse the "codemodel" and use that information for linking with rustc and friends. I should state however that the CMake codemodel is something [bordering on unusable][], but this isn't the first time the developers of cmake have shown they don't really know what they're doing.

That said, the current cmake crate doesn't use CMake as well as it should and it would require a complete and massive rewrite to get the functionality you need. As it stands it already assumes a few things which break under "poorly behaved projects". 

I should note that with the WG21 SG15 Tooling TR (a report that's being written to sort of standardize tooling without it being "a standard"), we're effectively going all in on JSON. Older tools will be more difficult handle

Luckily, I care about C++ and build tools and I'm a guru of the former and an expert in the latter so I'm sure we could get this resolved :)

[bordering on unusable]: https://cmake.org/cmake/help/latest/manual/cmake-file-api.7.html#codemodel-version-2

**Comment by dtolnay** [comment] 2020-02-25 07:41
As of https://travis-ci.com/dtolnay/cxx/builds/150429387 we now have windows CI on both x86_64-pc-windows-gnu and x86_64-pc-windows-msvc so I'll go ahead and close this issue. There is one warning emitted during the msvc build but we'll be following up on that in #44.

**Closed by dtolnay** 2020-02-25 07:41 UTC
