### ISSUE TITLE
CxxVector<SharedPtr<Type>>

### ISSUE THREAD

**Issue by smessmer** [dtolnay/cxx#774] opened 2021-03-26 21:07 UTC
For an opaque type `T`, the current implementation allows passing of `SharedPtr<T>` over the ffi boundary, but `CxxVector<SharedPtr<T>>` fails with

```
13 │ fn ROW(names: &CxxVector<CxxString>, types: &CxxVector<SharedPtr<Type>>) -> SharedPtr<RowType>;
   │                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^ unsupported vector target type
```

Similarly, `&Vec<SharedPtr<Type>>` doesn't work as an argument type to bridge functions either.

Note that such `CxxVector`s could also offer an API for push/pop since rust code can get `SharedPtr<T>` or `UniquePtr<T>` from other ffi calls.

**Comment by mikhailzagurskiy** [comment] 2021-03-27 04:15
This is because we don't have an implementation for CxxVecor target and VecTarget for the SharedPtr. I believe, that it will be supported in the future

**Comment by dtolnay** [comment] 2021-03-27 07:03
Yeah this is just not implemented yet because it hasn't come up. A workaround is to stick the shared ptr behind a shared struct, so it becomes a vector of structs, which is supported.

```rust
#[cxx::bridge]
mod ffi {
    struct SharedType {
        ptr: SharedPtr<Type>,
    }

    unsafe extern "C++" {
        type Type;
        type RowType;

        fn ROW(names: &CxxVector<CxxString>, types: &CxxVector<SharedType>) -> SharedPtr<RowType>;
    }
}
```

Or alternatively, to avoid modifying the C++ signature to deal with the wrapper struct on the C++ side, like this instead:

```rust
use cxx::{ExternType, SharedPtr};

#[repr(transparent)]
pub struct SharedType {
    ptr: SharedPtr<ffi::Type>,
}

unsafe impl ExternType for SharedType {
    type Id = cxx::type_id!("SharedType");
    type Kind = cxx::kind::Trivial;
}

#[cxx::bridge]
mod ffi {
    unsafe extern "C++" {
        include!("example/include/example.h");  // the real header declaring ROW

        type Type;
        type RowType;

        fn ROW(names: &CxxVector<CxxString>, types: &CxxVector<SharedType>) -> SharedPtr<RowType>;
    }

    extern "C++" {
        include!("example/include/shim.h");  // below

        type SharedType = crate::SharedType;
    }

    impl SharedPtr<Type> {}
}
```

```cpp
// shim.h

#pragma once
#include "example/include/example.h"  // header declaring Type
#include <memory>

using SharedType = std::shared_ptr<Type>;
```

**Comment by dtolnay** [comment] 2021-04-09 12:08
Closing as a duplicate of #741.

**Closed by dtolnay** 2021-04-09 12:08 UTC
Labels: help wanted
